FROM alpine
MAINTAINER arkinthesky.69@gmail.com 

RUN mkdir /app
WORKDIR /app
COPY . /app

ENV PATH="/root/.local/bin:${PATH}"

RUN apk update
RUN apk --no-cache add python3 python3-dev bash curl
RUN pip3 install --user pipenv
RUN pipenv install --system --dev

EXPOSE 5000
ENV FLASK_ENV="development"

CMD ["python3", "manage.py"]